# Generated by Django 5.1.3 on 2024-12-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_shift_signed_by_alter_shift_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='timesheet_generated',
            field=models.BooleanField(default=False),
        ),
    ]
