# Generated by Django 5.1.3 on 2024-12-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_remove_availability_day_availability_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
