# Generated by Django 5.1.3 on 2025-01-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
