# Generated by Django 5.1.3 on 2025-01-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
