# Generated by Django 5.1.3 on 2025-01-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='rate',
        ),
        migrations.AddField(
            model_name='location',
            name='saturday_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='location',
            name='sleep_in_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='location',
            name='sunday_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='location',
            name='weekday_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
