# Generated by Django 5.1.3 on 2025-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_remove_location_rate_location_saturday_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webpush_subscription',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
